"""
Main entrypoint for the Tidewave orchestrator.

This module exposes a FastAPI application instance that handles all backend
functionality for the Brandist AI orchestration pipeline. It routes user
requests to the appropriate tasks (deploying the frontend via Vercel webhooks,
running health checks, or generating plans with Anthropic's Claude models),
logs activities to Supabase, and returns unified JSON responses.

Do not edit this file manually unless you understand the integration points
between Render (for hosting), Vercel (for the frontend), n8n (for workflow
automation), Supabase (for logging), and Anthropic (for LLM calls).

Important environment variables (see `.env` or `render.yaml`):
    SUPABASE_URL, SUPABASE_KEY, ANTHROPIC_API_KEY,
    ANTHROPIC_API_URL, ANTHROPIC_API_VERSION,
    LLM_PROMOTION_THRESHOLD, LLM_MAX_TOKENS,
    VERCEL_HOOK_1, VERCEL_HOOK_2, API_HEALTH.

"""

from .current_app import app  # re-export the FastAPI instance

# Having this file ensures that `uvicorn main:app` works as expected and
# aligns with Render's default start command pattern. All routing and
# application logic lives in current_app.py.  Any additional startup or
# lifespan events should be added there.
